### ISSUE TITLE
unprintable string characters break cursor due to zero display width

### ISSUE THREAD

**Issue by therealplato** [iafan/goplayspace#18]
Trying to diagnose junk input bytes, I wanted to copy paste whatever it was
I did successfully turn bytes into invisible string and copy paste, but the editor broke:

https://goplay.space/#Xfsy91fp2Z
vs https://play.golang.org/p/Xfsy91fp2Z

**Comment by therealplato** [comment]
Might be fixed via #8

**Comment by iafan** [comment]
Do you mind sharing some screenshot/screencasting? I looked at your example, and it seems to be rendering properly for me. The non-printable characters inside the quotes are there, and caret behaves identically when going through them in both playgrounds.

**Comment by therealplato** [comment]
Should have mentioned I'm using firefox 55.0.3
https://www.youtube.com/watch?v=xbss4NGHWxM

**Comment by iafan** [comment]
Thanks. I can reproduce these in FF. The reason is that FF renders these characters differently in textarea and in regular HTML (which rather looks like a bug on FF side). If you disable syntax highlighting in settings in Go Play Space, you will see what I mean. Not sure if this is fixable on my side, unless I completely change the editor component.
