### ISSUE TITLE
Add snippets management

### ISSUE THREAD

**Issue by jostyee** [iafan/goplayspace#4]
RT. It'd be much more convenient to organize code snippets via this tool.

**Comment by iafan** [comment]
Go Play Space currently works with the official Go Playground servers (and the plan is to remain such a frontend), which means there's no way to e.g. list or delete snippets, and all these snippets are essentially public (but not published) and anonymous.

But even with this limitation, I can see a benefit of having some sort of publicly searchable registry of snippets. Wish it was a part of official Go Playground, though.

**Comment by jostyee** [comment]
@iafan Thanks for your reply.

**Comment by jostyee** [comment]
@iafan How about switch to gist.github.com to store snippets?

**Comment by iafan** [comment]
I think this is still beyond the current scope of the project, and requires significant development efforts. I assume that Go Playground is usually used for a throw-away code; in cases when you want to save your snippet, you can just copy-paste your code somewhere (e.g. into a new Gist), or you can use the Share function and just bookmark the URL, so that you always have your snippets in the browser.

Since the code for Go Play Space is open-sourced, you may want to try experimenting with GitHub integration to see if this is something that would work for you as you imagine, and if its worth the effort.
